services:
    bot:
        container_name: plane_bot
        image: node:slim
        volumes:
            # Bot
            - ./bot:/bot
            - ./package.json:/bot/package.json
            - ./package-lock.json:/bot/package-lock.json
            - ./src/config.json:/bot/config.json
            - ./src/RAFK.json:/bot/RAFK.json
            - ./src/air_rec.json:/bot/air_rec.json
        working_dir: /bot
        entrypoint: /bot/entrypoint.sh
