services:
    redis:
        container_name: plane_redis
        image: redis:latest
        # sysctls:
        #     - vm.overcommit_memory=1
    bot:
        container_name: plane_bot
        image: node:slim
        volumes:
            - ./bot/:/bot/
            - ./package.json:/bot/package.json
            - ./package-lock.json:/bot/package-lock.json
            - ./src/config.json:/bot/config.json

            - ./src/RAFK.json:/bot/RAFK.json
            - ./src/air_rec.json:/bot/air_rec.json
            - ./src/waifus.json:/bot/waifus.json
            - ./src/assets/:/bot/assets/
        working_dir: /bot
        entrypoint: /bot/entrypoint.sh
        depends_on:
            - redis
