services:
    bot:
        container_name: plane_bot
        image: node:slim
        volumes:
            - ./:/bot/
        working_dir: /bot
        entrypoint: /bot/entrypoint.sh
        extra_hosts:
            - "host.docker.internal:host-gateway"
